#smtp邮件发送
email:
#smtp服务器
  smtp: smtp.qq.com
#smtp服务器端口
  port: 25
#发信邮箱
  from: 123@qq.com
#发信邮箱密码 非邮箱密码而是创建的smtp的密码
  key: abcdefg
#收信邮箱 可以多个
  to:
   - 1@qq.com
   - 1@gmail.com
# pushplus推送 官网 https://www.pushplus.plus/
push_plus:
#push_plus 你的token
  token: abcdefg
#推送通道
  channel:
#mail 邮箱
    - mail
#微信
    # - wechat
#企业微信
    # - webhook
#钉钉
    # - cp
#短信
    # - sms


  
